puts "Hello Github! Octocats are amazing"
puts "Something"
puts "Matts"
puts "Elijah"
puts "Bryce"
puts "Mihir"
puts "Keelan"
puts "Nithya"
puts "Mr. Padjen"
puts "Derek"
puts "Ben"
puts "David"
puts "Jett"
puts "Charlie"
puts "Nikki"
